name: cleanup after pull request

on:
  pull_request:
    types:
    - closed

jobs:
  delete_images:
    runs-on: ubuntu-latest
    steps:
    - uses: snok/container-retention-policy@v2
      with:
        account-type: personal
        token: ${{ secrets.GH_PAT_DELETE_PACKAGES }}
        image-names: "*"
        cut-off: One min ago UTC
        filter-tags: pr-${{ github.event.pull_request.number }}, *-pr-${{ github.event.pull_request.number }}
