name: release

on:
  push:
    branches:
      - main
    # can't find a way to ignore all root files
    paths-ignore:
      - .github/**
      - .devcontainer.json
      - .gitmodules
      - archive
      - LICENSE
      - README.md
  workflow_dispatch:
    inputs:
      images:
        description: Image folder names as JSON array
        required: true
        type: string

jobs:
  get-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      images: ${{ steps.folders-condition.outputs.folders }}
    steps:
    - name: Checkout repository
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v3
      continue-on-error: true # submodules don't seem to inherit the SSH key, so private repos fail
      with:
        fetch-depth: 0
        submodules: true
        ssh-key: ${{ secrets.GIT_SSH_KEY }}

    # TODO not detecting submodule changes properly. possibly related to checkout err on private repo?
    # https://github.com/tj-actions/changed-files/pull/394/files
    - name: Get changed files
      if: ${{ github.event_name != 'workflow_dispatch' }}
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true # output folders instead of files
        dir_names_max_depth: 1 # only return roots, not subfolders
        json: true # output in matrix JSON format
        files_ignore: .gitmodules

    - id: folders-condition
      run: echo "folders=${{ github.event_name == 'workflow_dispatch' && inputs.images || steps.changed-files.outputs.all_changed_and_modified_files }}" >> $GITHUB_OUTPUT

  build:
    needs: get-images
    continue-on-error: true # push tags even if some architectures fail
    strategy:
      fail-fast: false # allows visibility of multiarch support
      matrix:
        image: ${{ fromJson(needs.get-images.outputs.images) }}
        os:
        - ubuntu-latest
        - buildjet-2vcpu-ubuntu-2204-arm
        - windows-latest
        include:
        - os: ubuntu-latest
          arch: linux/amd64
        - os: buildjet-2vcpu-ubuntu-2204-arm
          arch: linux/arm64
        - os: windows-latest
          arch: windows/amd64
          ext: .windows
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
      id-token: write # OIDC artifact signing
    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
    
      # required for builds with custom context
      # https://stackoverflow.com/a/52269934
      # can't use github.repositoryUrl - it uses git://, which seems to be blocked on Windows runners
      - name: Checkout image folder
        run: |
          git clone -n --depth=1 --filter=tree:0 ${{ github.server_url }}/${{ github.repository }} ./
          git sparse-checkout set --no-cone ${{ matrix.image }}
          git checkout ${{ github.sha }}

      - name: Init submodule if present
        id: get-context
        continue-on-error: true
        run: |
          git submodule update --init --recursive $CONTEXT
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT
        env:
          CONTEXT: ${{ matrix.image }}/${{ matrix.image }}

      - name: Copy patches to submodule (Linux)
        if: ${{ steps.get-context.outputs.context && startsWith(matrix.arch, 'linux/') }}
        continue-on-error: true
        run: |
          shopt -s extglob
          cp !(${{ matrix.image }}) ${{ matrix.image }} -r

      - name: Copy patches to submodule (Windows)
        if: ${{ steps.get-context.outputs.context && startsWith(matrix.arch, 'windows/') }}
        continue-on-error: true
        working-directory: ${{ matrix.image }}
        run: cp * ${{ matrix.image }} -r

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          tags: type=sha

      # format labels for build action
      - uses: frabert/replace-string-action@v2
        id: format-labels
        with:
          pattern: '\n'
          string: ${{ steps.meta.outputs.labels }}
          replace-with: '",'
          flags: 'g'
      - uses: frabert/replace-string-action@v2
        id: format-labels-2
        with:
          pattern: '='
          string: ${{ steps.format-labels.outputs.replaced }}
          replace-with: '="'
          flags: 'g'

      # format arch for image tag
      - uses: frabert/replace-string-action@v2
        id: format-labels-tag
        with:
          pattern: '/'
          string: ${{ matrix.arch }}
          replace-with: '-'
          flags: 'g'

      - name: Check if Dockerfile exists
        id: dockerfileexists
        working-directory: ${{ steps.get-context.outputs.context || matrix.image }}
        run: ls Dockerfile${{ matrix.ext }}
        continue-on-error: true

      # can we use arch in here? suspect windows images could slow linux down otherwise
      # confirmed - particularly bad for off-net ARM64 workers, 3+ minutes
      # https://github.com/satackey/action-docker-layer-caching/issues/169#issuecomment-1217408538
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        if: ${{ steps.dockerfileexists.outcome == 'success' }}
        continue-on-error: true
        with:
          key: docker-layer-cache-${{ matrix.image }}-${{ steps.format-labels-tag.outputs.replaced }}-{hash}
          restore-keys: |
            docker-layer-cache-${{ matrix.image }}-${{ steps.format-labels-tag.outputs.replaced }}-
            layer-docker-layer-cache-${{ matrix.image }}-${{ steps.format-labels-tag.outputs.replaced }}-

      # docker/build-push-action#18 doesn't support Windows
      # this action doesn't have caching though
      - uses: mr-smithers-excellent/docker-build-push@v6
        if: ${{ steps.dockerfileexists.outcome == 'success' }}
        id: build-push
        with:
          image: ${{ matrix.image }} #
          registry: ghcr.io #
          username: ${{ github.actor }} #
          password: ${{ github.token }} #
          directory: ${{ steps.get-context.outputs.context || matrix.image }}
          dockerfile: ${{ steps.get-context.outputs.context || matrix.image }}/Dockerfile${{ matrix.ext }}
          tags: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}-${{ steps.format-labels-tag.outputs.replaced }}
          labels: ${{ steps.format-labels-2.outputs.replaced }}"

      - uses: sigstore/cosign-installer@v3.0.5
      - if: ${{ steps.dockerfileexists.outcome == 'success' }}
        run: cosign sign --yes ${{ steps.build-push.outputs.imageFullName }}:${{ steps.build-push.outputs.tags }}
      
      # workaround for lack of matrix support in job.outputs. was almost done, but the team got laid off
      # https://github.com/actions/runner/pull/2477#issuecomment-1501003600
      - if: ${{ steps.dockerfileexists.outcome == 'success' }}
        run: echo '["${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}","${{ steps.build-push.outputs.tags }}"]' > tags
      - uses: actions/upload-artifact@v3
        if: ${{ steps.dockerfileexists.outcome == 'success' }}
        with:
          name: ${{ matrix.image }}-${{ hashFiles('tags') || 'none' }}
          path: tags
          if-no-files-found: warn

  manifest:
    needs:
    - get-images
    - build
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.get-images.outputs.images) }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write # OIDC artifact signing
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
  
    - uses: actions/download-artifact@v3
    - id: tags
      run: |
        ls
        shopt -s extglob
        tags="$(cat ${{ matrix.image }}-*/tags | jq --slurp -c 'map(.[] |= "ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:\(.)") | { tag: .[0][0], images: ([.[][1]] | join(",")) }')"
        echo "tags=$tags" >> $GITHUB_OUTPUT
        echo $tags

    - name: Create and push manifest images
      uses: Noelware/docker-manifest-action@0.3.1
      with:
        inputs: ${{ fromJson(steps.tags.outputs.tags)['tag'] }}
        images: ${{ fromJson(steps.tags.outputs.tags)['images'] }}
        push: true

    - uses: sigstore/cosign-installer@v3.0.5
    - run: cosign sign --yes ${{ fromJson(steps.tags.outputs.tags)['tag'] }}
