name: release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - LICENSE
      - README.md
  workflow_dispatch:
    inputs:
      images:
        description: Image folder names as JSON array
        required: true
        type: string

jobs:
  get-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      images: ${{ steps.folders-condition.outputs.folders }}
    steps:
    - name: Checkout repository
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        ssh-key: ${{ secrets.GIT_SSH_KEY }}

    - name: Get changed files
      if: ${{ github.event_name != 'workflow_dispatch' }}
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true # output folders instead of files
        dir_names_max_depth: 1 # only return roots, not subfolders
        json: true # output in matrix JSON format
        json_raw_format: true
        files_ignore: .github

    - id: folders-condition
      run: echo "folders=${{ github.event_name == 'workflow_dispatch' && inputs.images || steps.changed-files.outputs.all_changed_and_modified_files }}" >> $GITHUB_OUTPUT

  docker:
    needs: get-images
    strategy:
      fail-fast: false # allows visibility of multiarch support
      matrix:
        image: ${{ fromJson(needs.get-images.outputs.images) }}
        include:
        - arch: linux/amd64
          os: ubuntu-latest
        - arch: linux/arm64
          os: buildjet-2vcpu-ubuntu-2204-arm
        - arch: windows/amd64
          os: windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
      actions: write
    steps:
      # required for builds with custom context
      # https://stackoverflow.com/a/52269934
      # can't use github.repositoryUrl - it uses git://, which seems to be blocked on Windows runners
      - name: Checkout image folder
        run: |
          git clone -n --depth=1 --filter=tree:0 ${{ github.server_url }}/${{ github.repository }} .
          ls
          cd ${{ matrix.image }}
          git sparse-checkout set --no-cone ${{ matrix.image }}
          git checkout ${{ github.sha }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          tags: type=sha

      - name: Patch submodule if present
        id: get-context
        run: |
          cd $IMAGE
          git submodule update --init --recursive $IMAGE && cp * $IMAGE -r
          echo "context=$IMAGE/$IMAGE" >> $GITHUB_OUTPUT
        continue-on-error: true
        env:
          IMAGE: ${{ matrix.image }}

      # - uses: docker/setup-buildx-action@v2

      # format labels for build action
      - uses: frabert/replace-string-action@v2
        id: format-labels
        with:
          pattern: '\n'
          string: ${{ steps.meta.outputs.labels }}
          replace-with: '",'
          flags: 'g'
      - uses: frabert/replace-string-action@v2
        id: format-labels-2
        with:
          pattern: '='
          string: ${{ steps.format-labels.outputs.replaced }}
          replace-with: '="'
          flags: 'g'

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
        with:
          key: docker-layer-cache-{hash}
          restore-keys: |
            docker-layer-cache-
            layer-docker-layer-cache-

      # docker/build-push-action#18 doesn't support Windows
      # this action doesn't have caching though
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ matrix.image }} #
          registry: ghcr.io #
          username: ${{ github.actor }} #
          password: ${{ github.token }} #
          directory: ${{ steps.get-context.outputs.context || matrix.image }} # context:
          dockerfile: ${{ steps.get-context.outputs.context || matrix.image }}/Dockerfile
          # platform: ${{ matrix.arch }}
          tags: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }} # ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.format-labels-2.outputs.replaced }}"
